defmodule MyAshBlog.Repo.Migrations.UpdatePolicies do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :is_author, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:users) do
      remove :is_author
    end
  end
end
