defmodule MyAshBlog.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      modify :content, :text, null: false

      add :author_id,
          references(:authors,
            column: :id,
            name: "posts_author_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:comments) do
      add :user_id,
          references(:users,
            column: :id,
            name: "comments_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :post_id,
          references(:posts,
            column: :id,
            name: "comments_post_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:comments, "comments_user_id_fkey")

    drop constraint(:comments, "comments_post_id_fkey")

    alter table(:comments) do
      remove :post_id
      remove :user_id
    end

    drop constraint(:posts, "posts_author_id_fkey")

    alter table(:posts) do
      remove :author_id
      modify :content, :text, null: true
    end
  end
end
