defmodule MyAshBlog.Repo.Migrations.MigrateResources7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def change do
    alter table(:users) do
      remove :hashed_password
    end
  end
end
